### PR TITLE
Fix for easy-mail 0.8.0-SNAPSHOT compatibility

### PR DESCRIPTION
**Pull request by oexza**

### CODE REVIEW

**Comment by joscha** [comment]
Thanks for this. I think before merging this I want to revisit moving the constants from the interface into the implementation - it seems as if the abstraction we had in play-easymail is not really given any more. It seems as if using it became more complex with the last snapshot unfortunately.

**Comment by oexza** [comment]
@joscha you do have a point. i should have made the implementation as
lean as possible. i'll see to it in a bit

**Comment by oexza** [comment]
ok i've submitted a pr on the easymail project

**Comment by joscha** [comment]
I think that overlapped with my changes...

**Comment by joscha** [comment]
closed via db2bdb9

**Pull request closed without merging**
