### PR TITLE
Added message.id

### PR DESCRIPTION
**Pull request by ibnuda**
Added Indonesian translation.

### CODE REVIEW

**Comment by joscha** [comment]
nice, can you change this, so it doesn't delete the English message file?

**Comment by ibnuda** [comment]
should i create another pull request which contains the fixes, joscha?

**Comment by joscha** [comment]
Nope, this one is fine, thank you!

**Comment by joscha** [comment]
I will merge this, if you have more time, it would also be cool if this file could be translated: https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/conf/messages.en

**Comment by ibnuda** [comment]
sure. will do.

**Comment by joscha** [comment]
Thank you!

**Pull request merged**
