### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by PromanSEW**
I want to help with translation for messages in Russian
I think I translated them right

### CODE REVIEW

**Comment by joscha** [comment]
Hi @PromanSEW, thank you for that - would you mind all's translating the other strings before I merge it? There are a couple more language files.

**Comment by PromanSEW** [comment]
I will add them? Thanks

**Comment by PromanSEW** [comment]
Something else?

**Comment by joscha** [comment]
Thank you very much!

**Pull request merged**
