### PR TITLE
Support for DI, removing Plugins

### PR DESCRIPTION
**Pull request by raunak**
+ Removed use of Plugins in AuthProvider
+ Deprecated UserServicePlugin
+ Created UserServiceImpl (which should be extended by user now)
+ Replaced Application from AuthProvider constructor and updated with ApplicationLifeCycle

Guide used: https://www.playframework.com/documentation/2.4.x/PluginsToModules

### CODE REVIEW

**Comment by mkurz** [comment]
@raunak You have to add
```
routesGenerator := InjectedRoutesGenerator
```
to (all?) `build.sbt` files. See https://www.playframework.com/documentation/2.4.x/JavaRouting#Dependency-Injection

**Comment by raunak** [comment]
@mkurz any ideas why this is still failing?

**Comment by mkurz** [comment]
@raunak Why did you close this pull request?

**Comment by raunak** [comment]
@mkurz I wanted to create a proper fix first, afterwards I'll re-create the pull request.

**Comment by joscha** [comment]
I think once this is done, we might move playAuthenticate to the org and split up the repositories in code and samples, etc.

**Pull request closed without merging**
