### PR TITLE
Fix saveManyToManyAssociations calls

### PR DESCRIPTION
**Pull request by slimandslam**
Fixes saveManyToManyAssociations calls when you uncomment them.

### CODE REVIEW

**Comment by slimandslam** [comment]
Oops. Ok, maybe it doesn't need that import.  :-)

**Comment by joscha** [comment]
;) Could you remove it and rebase the branch please?

**Comment by slimandslam** [comment]
I'd be happy to but I don't know how. Can you provide the steps?

Cheers,

J

**Comment by joscha** [comment]
Fixed in 0f528cecb9936e9e16b69204a92b5824eeaefd07

**Pull request merged**
