### PR TITLE
[Fix] Fixed french errors messages.

### PR DESCRIPTION
**Pull request by nblavoie**
Fixed the french error messages.

### CODE REVIEW

**Comment by mkurz** [comment]
@nblavoie Could you please add an empty line between line 5 and 6? Thanks!

**Comment by nblavoie** [comment]
@mkurz Done.

**Comment by mkurz** [comment]
@joscha I don't speak french, what do you think?

**Comment by nblavoie** [comment]
The errors are explicite and easier to grasp for a french speaking user. They are a bit less technical and but the end-user will better understand the issues they are facing if any errors are thrown.

**Comment by joscha** [comment]
Merci beacuoup :fr: !

**Comment by nblavoie** [comment]
Thanks @joscha :)

**Pull request merged**
