### PR TITLE
Added injected Authenticate controller

### LINKED ISSUE #267: Provide DI Authenticate controller
See https://groups.google.com/forum/?fromgroups#!topic/play-framework/IrMKSik-kw8

@joscha Basically I would copy [Authenticate.java](https://github.com/joscha/play-authenticate/blob/5d0b8c6dd915ffe0ac4177f1fd2c982a84e18461/code/app/com/feth/play/module/pa/controllers/Authenticate.java), name it `AuthenticateDI.java` and remove the static keyword. What do you think?

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #267

### CODE REVIEW

**Comment by mkurz** [comment]
I added a superclass `AuthenticateBase` to avoid duplicate code.

**Comment by mkurz** [comment]
@joscha Build is green

**Comment by joscha** [comment]
woop, go for it then, joy of merging and stuff ;)

**Comment by mkurz** [comment]
Sure - I just want to make sure my stuff gets reviews :smile:

**Comment by dan-lind** [comment]
Will this now be available in the 0.7.0—snapshot?

**Comment by joscha** [comment]
yes as soon as the build in master (https://travis-ci.org/joscha/play-authenticate/builds/69432667) is done

**Pull request merged**
